### ISSUE TITLE
Move project to LVGL org?

### ISSUE THREAD

**Issue by nia-e** [lvgl/lv_binding_rust#101]
Was suggested here: https://forum.lvgl.io/t/rust-bindings-for-lvgl-updated/11406

Should we do this?

**Comment by rafaelcaricio** [comment]
Yes, I wanted to ask if you want to move. I think it is a good idea.

**Comment by nia-e** [comment]
There's an update on the linked thread as to how to proceed

**Comment by kisvegabor** [comment]
Transferred. Now it's under the LVGL organization. 

Thank you very much! I'm sure the Rust binding will make a lot of users happy. :blush:
