### ISSUE TITLE
Isolate build display from update (DrawBuffer ???) 

### ISSUE THREAD

**Issue by fulup-bzh** [lvgl/lv_binding_rust#148]
I run an asynchronous application, where display construction if done at init time and update from an independant asynchronous timer. I started from ```arc``` sample implementing the construction in one routine and display update in an other. When trying to update the window I get a core dump, I suspect ```DrawBuffer``` or an other holding handle to be wipe out when returning from init routine. 

Question: which are the handle I should keep track of to make sure that my display does not get wipe out from stack when returning from my init routine ? (using arc sample as base)

Note:  In order to keep different display handles from being wipe out at return my routine returns. 
```
       return DisplayHandle {
           sim_display,
            window,
            arc,
            display,
        }
```
I cannot return buffer coming from DrawBuffer because it of its type that depends in the definition.

My timer async routine fail in lvgl::task_handler() 
```
  pub fn tick_update(&mut self, tick: Duration) {

        // update internal lvgl tick timer
        lvgl::tick_inc(tick);

        // exec any lvgl pending task/action
        lvgl::task_handler();
}
```

**Comment by fulup-bzh** [comment]
For information debugger trace.
![image](https://github.com/lvgl/lv_binding_rust/assets/7931186/2e87fcf8-4ee8-49e5-9a06-221ee41b1a03)

**Comment by nia-e** [comment]
Are you moving the actual display between threads? If so, handling this case is still an open question; see https://github.com/lvgl/lv_binding_rust/issues/140. I was trying to partially fix this in https://github.com/lvgl/lv_binding_rust/pull/144/ but I haven't had time to work on this project recently

**Comment by fulup-bzh** [comment]
Potential display widgets may may change value/status from a different thread. Nevertheless the update action handle from a timer always come from the same thread.
The issue seems more to be that when returning from my create function, some LVGL handle are free. I'm expecially afrby Drawbuffer could reserve memory in stack and not in a Box::leak

**Comment by fulup-bzh** [comment]
Digging further, I found a warning that alarm me.
```
```

**Comment by nia-e** [comment]
I believe that has since been patched, it should be fine on latest git master?

**Comment by fulup-bzh** [comment]
I updated to master without more success. To make this clearer to follow I propose to close this thread and reopen a new cleaner one on "updating display from an independent context"
